#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out
# sbatch install_environment.job

module purge
module load 2022
module load Anaconda3/2022.05

cd /home/aochotorenalay/3d_breast_reconstruction/snellius

conda create -n msc_thesis python=3.10.13

source activate msc_thesis
pip install -r requirements.txt


