#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=12:00:00
#SBATCH --output=/slurm_files/neural_network_run_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate msc_thesis

cd /home/aochotorenalay/3d_breast_reconstruction

# Check whether the GPU is available
srun python train.py